

version: '3.8'

### NOTIFICATIONS SERVICE ###

services:

  # minio:
  #   image: minio/minio
  #   ports:
  #     - 9093:9093
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - ./data:/data
  #   command: server --address ":9093" \data
  #   networks:
  #     - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka-network
    network_mode: bridge

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    networks:
      - kafka-network
  
  clamav:
    image: mkodockx/docker-clamav:alpine
    ports:
      - 3310:3310
    networks:
      - kafka-network

  virus-file-scanner-service:
    build: virus-file-scanner-service
    ports:
      - "8088:8088"
    depends_on:
      # - minio
      - kafka
      - clamav
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafka-network

networks:
  kafka-network:


#############################